name: my_pati
description: Telling about Pati Regency, a small regency in Central Java province 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon_app.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "images/icon_app.png"
  windows:
    generate: true
    image_path: "images/icon_app.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/icon_app.png"


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
        - asset: fonts/Lato/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700
